# Generated by Django 4.2 on 2023-04-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='x_item_name_2f968d_idx',
            old_fields=('name', 'value'),
        ),
    ]
